# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.user.extension:
        class: AppBundle\Service\UserExtensionService
        autowire: true

    app.mailer:
        class: AppBundle\Service\MailerService
        arguments: ["%notification.prefix%", "%notification.email_from%", "@mailer", "@translator"]

    app.account.security_listener:
        class: AppBundle\Listener\SecurityListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    app.account.request_listener:
        class: AppBundle\Listener\RequestListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app.entity.organization_voter:
        class: AppBundle\Security\OrganizationVoter
        autowire: true
        public: false
        tags:
            - { name: security.voter }

    app.entity.enumeration_voter:
        class: AppBundle\Security\EnumerationVoter
        autowire: true
        public: false
        tags:
            - { name: security.voter }

    app.entity.profile_voter:
        class: AppBundle\Security\ProfileVoter
        autowire: true
        public: false
        tags:
            - { name: security.voter }

    app.entity.user_voter:
        class: AppBundle\Security\UserVoter
        autowire: true
        public: false
        tags:
            - { name: security.voter }

    app.menu_builders_chain:
        class: AppBundle\Service\MenuBuilderChain

    app.form.extended_element:
        class: AppBundle\Form\Type\ExtendedElementType
        autowire: true
        tags:
            - { name: form.type }
