parameters:


services:
    atica.core_bundle.user.extension:
        class: IesOretania\AticaCoreBundle\Service\UserExtensionService
        autowire: true

    atica.core_bundle.menu_builder:
        class: IesOretania\AticaCoreBundle\Service\CoreMenuBuilderService
        arguments: ['@security.authorization_checker', '@session', '@doctrine.orm.entity_manager']
        tags:
            -  { name: atica.menu_builder }
