parameters:


services:
    atica.core_bundle.user.extension:
        class: IesOretania\AticaCoreBundle\Service\UserExtensionService
        autowire: true

    atica.core_bundle.menu:
        class: IesOretania\AticaCoreBundle\Service\CoreMenu
        arguments: ['@atica.core_bundle.user.extension']
        tags:
            -  { name: atica_core.menu_builder }
